// <auto-generated />
namespace AuthorUser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class claim1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(claim1));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251753212_claim1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
